[build]
  publish = "."
  command = "echo 'Static site ready'"

[[redirects]]
  from = "/"
  to = "/indice_general.html"
  status = 200

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"